#!/bin/bash

echo "Intializing replica cfg replica set"
replicate="rs.initiate(); sleep(1000); cfg = rs.conf(); cfg.members[0].host = \"mongocfg1\"; rs.reconfig(cfg); rs.add(\"mongocfg2\"); rs.add(\"mongocfg3\"); rs.status();"
docker exec -it mongocfg1 bash -c "echo '${replicate}' | mongo"

sleep 2

echo "Intializing shards"
for (( rs = 1; rs < 3; rs++ )); do
  echo "Intializing replica ${rs} set"
  replicate="rs.initiate(); sleep(1000); cfg = rs.conf(); cfg.members[0].host = \"mongors${rs}n1\"; rs.reconfig(cfg); rs.add(\"mongors${rs}n2\"); rs.add(\"mongors${rs}n3\"); rs.status();"
  docker exec -it mongors${rs}n1 bash -c "echo '${replicate}' | mongo"
done

sleep 2

docker exec -it mongos1 bash -c "echo \"sh.addShard('mongors1/mongors1n1:27017'); sh.addShard('mongors2/mongors2n1:27017');\" | mongo "
